import express from 'express';
import multer from 'multer';
import streamifier from 'streamifier';
import ffmpeg from 'fluent-ffmpeg';
import ffmpegInstaller from '@ffmpeg-installer/ffmpeg';
import authMiddleware from '../middleware/auth.js';
import AudioRecording from '../models/AudioRecording.js';
import OrganizationData from '../models/OrganizationData.js';
import { PassThrough } from 'stream';
import { AssemblyAI } from 'assemblyai'; // Free Tier API for Diarization
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const aiClient = new AssemblyAI({ apiKey: process.env.ASSEMBLYAI_API_KEY || 'YOUR_ASSEMBLYAI_KEY_HERE' }); // Get from assemblyai.com

ffmpeg.setFfmpegPath(ffmpegInstaller.path);

const router = express.Router();

// Using MemoryStorage to keep the file buffer in memory and save directly to MongoDB
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

// Upload Endpoint
router.post('/upload', authMiddleware, upload.single('audioFile'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: 'No file uploaded' });
    }

    console.log("Processing audio with deeply enhanced FFmpeg AI...");
    
    // Parse the incoming free transcript timestamps generated by Google Chrome native ML
    let transcriptObj = [];
    if (req.body.transcriptData) {
      try {
        transcriptObj = JSON.parse(req.body.transcriptData);
      } catch (e) {
        console.error("Failed to parse transcript", e);
      }
    }

    // Create a stream from the uploaded raw audio buffer
    const inputStream = streamifier.createReadStream(req.file.buffer);
    const passThrough = new PassThrough();
    const chunks = [];

    // Collect processed chunks
    passThrough.on('data', chunk => chunks.push(chunk));

    // When processing is totally finished, save to DB
    passThrough.on('end', async () => {
      const enhancedBuffer = Buffer.concat(chunks);

      const newRecording = new AudioRecording({
        userId: req.user.id,
        filename: `recording-${Date.now()}.mp3`, // Changed to mp3 for universal high quality compatibility
        audioData: enhancedBuffer,
        contentType: 'audio/mp3',
        transcript: transcriptObj // Save timestamps and text to the DB natively
      });

      await newRecording.save();
      console.log('Audio processed and perfectly saved to MongoDB!');

      res.status(201).json({
        message: 'File uploaded and enhanced successfully',
        recording: {
          _id: newRecording._id,
          filename: newRecording.filename,
          createdAt: newRecording.createdAt
        }
      });

      // Automatically trigger Deep Diarization in the background!
      (async () => {
        try {
          console.log(`[Auto-Mation] Starting background transcription for recording: ${newRecording._id}`);
          const transcriptInfo = await aiClient.transcripts.transcribe({
             audio: enhancedBuffer, 
             speaker_labels: true,
             speech_models: ["universal-3-pro"]
          });

          if (transcriptInfo.status !== 'error') {
            const SILENCE_THRESHOLD = 1500; 
            const finalBlocks = [];
            let currentBlock = null;

            if (transcriptInfo.words && transcriptInfo.words.length > 0) {
              transcriptInfo.words.forEach(word => {
                if (!currentBlock) {
                  currentBlock = { text: word.text, timestamp: word.start, endTime: word.end, speaker: word.speaker };
                } else {
                  if (word.speaker === currentBlock.speaker && (word.start - currentBlock.endTime) <= SILENCE_THRESHOLD) {
                    currentBlock.text += " " + word.text;
                    currentBlock.endTime = word.end;
                  } else {
                    finalBlocks.push(currentBlock);
                    currentBlock = { text: word.text, timestamp: word.start, endTime: word.end, speaker: word.speaker };
                  }
                }
              });
              if (currentBlock) finalBlocks.push(currentBlock);
            } else {
              finalBlocks.push(...(transcriptInfo.utterances || []).map(u => ({
                text: u.text, timestamp: u.start, endTime: u.end, speaker: u.speaker
              })));
            }

            await AudioRecording.findByIdAndUpdate(newRecording._id, { transcript: finalBlocks });
            console.log(`[Auto-Mation] Background transcription fully finished for recording: ${newRecording._id}`);
          }
        } catch (err) {
          console.error('[Auto-Mation] Background transcription failed:', err);
        }
      })();
    });

    // FFmpeg Processing Pipeline
    ffmpeg(inputStream)
      .audioCodec('libmp3lame')
      .audioBitrate('192k')     // Heavy encoding bitrate for deep clarity
      .audioChannels(1)         // Force Mono (centers the voice track natively)
      .audioFilters([
        'volume=5.0',           // MASSIVE Volume Boost right at the start to ensure low voices are caught!
        'highpass=f=80',        // EQ: Drops heavy AC rumbling, car noise, desk bumps
        'lowpass=f=8000',       // EQ: Cuts white noise/hissing artifacts above 8kHz
        'afftdn=nf=-20',        // AI: Mild noise reduction so we don't accidentally cut out quiet voices
        'loudnorm=I=-12:TP=-1.0:LRA=7' // EBU R128 Broadcast loudnorm pushed heavily to podcast standard levels
      ])
      .format('mp3')
      .on('error', (err) => {
        console.error('FFmpeg Audio Processing Error:', err);
        if (!res.headersSent) {
          res.status(500).json({ message: 'Error running FFmpeg audio enhancement framework' });
        }
      })
      .pipe(passThrough);

  } catch (err) {
    console.error('Upload Error:', err);
    res.status(500).json({ message: 'Server error during upload' });
  }
});

// Post-Processing: Run AI Diarization
router.post('/:id/transcribe', authMiddleware, async (req, res) => {
  try {
    const recording = await AudioRecording.findOne({ _id: req.params.id, userId: req.user.id });
    if (!recording) return res.status(404).json({ error: 'Recording not found' });
    
    // Convert DB buffer into format AssemblyAI accepts (requires handling Buffer properly or URL)
    // AssemblyAI handles streams/buffers natively in newer SDK
    const transcriptInfo = await aiClient.transcripts.transcribe({
       audio: recording.audioData, 
       speaker_labels: true, // True speaker separation (Diarization)
       speech_models: ["universal-3-pro"] // Updated AssemblyAI API requires this exactly as an array map!
    });
    
    if (transcriptInfo.status === 'error') {
       throw new Error(transcriptInfo.error);
    }
    
    // Rebuild utterances manually from word-level precision!
    // We split a speaker's text block if there is a silence of > 1500 milliseconds
    const SILENCE_THRESHOLD = 1500; 
    const finalBlocks = [];
    let currentBlock = null;

    if (transcriptInfo.words && transcriptInfo.words.length > 0) {
      transcriptInfo.words.forEach(word => {
        if (!currentBlock) {
          currentBlock = { 
            text: word.text, 
            timestamp: word.start, 
            endTime: word.end, 
            speaker: word.speaker 
          };
        } else {
          // If the same speaker is still talking AND the silence gap is less than our threshold
          if (word.speaker === currentBlock.speaker && (word.start - currentBlock.endTime) <= SILENCE_THRESHOLD) {
            currentBlock.text += " " + word.text; // Append voice
            currentBlock.endTime = word.end;      // Extend time
          } else {
            // A long silence happened OR the speaker changed! Save this chunk and start a new one.
            finalBlocks.push(currentBlock);
            currentBlock = { 
              text: word.text, 
              timestamp: word.start, 
              endTime: word.end, 
              speaker: word.speaker 
            };
          }
        }
      });
      // Don't forget to push the very last block
      if (currentBlock) {
        finalBlocks.push(currentBlock);
      }
    } else {
      // Fallback to AssemblyAI's default utterances if words aren't available for some reason
      finalBlocks.push(...(transcriptInfo.utterances || []).map(u => ({
        text: u.text,
        timestamp: u.start,
        endTime: u.end,
        speaker: u.speaker
      })));
    }

    recording.transcript = finalBlocks;
    await recording.save();

    res.json({ message: 'Diarization successful', transcript: finalBlocks });
  } catch (err) {
    console.error('Diarization Error:', err);
    res.status(500).json({ error: 'AI Transcription failed. Make sure valid AssemblyAI API key is set.' });
  }
});

// Get User's Recordings List
router.get('/mine', authMiddleware, async (req, res) => {
  try {
    // Return all records but exclude the massive audioData buffer for the list
    const recordings = await AudioRecording.find({ userId: req.user.id })
      .select('-audioData')
      .populate('userId', 'name email')
      .sort({ createdAt: -1 });
      
    res.json(recordings);
  } catch (err) {
    console.error('Fetch Recordings Error:', err);
    res.status(500).json({ message: 'Server error while fetching recordings' });
  }
});

// Update Meeting Name for a recording
router.put('/:id/meeting', authMiddleware, async (req, res) => {
  try {
    const { meetingName } = req.body;
    const recording = await AudioRecording.findOneAndUpdate(
      { _id: req.params.id, userId: req.user.id },
      { meetingName },
      { new: true }
    ).select('-audioData');
    
    if (!recording) return res.status(404).json({ error: 'Recording not found' });
    res.json(recording);
  } catch (err) {
    res.status(500).json({ error: 'Failed to update meeting name' });
  }
});

// Organization: Get all unique meeting names
router.get('/organization/meetings', authMiddleware, async (req, res) => {
  try {
    const meetingNames = await AudioRecording.distinct('meetingName', { meetingName: { $ne: 'Unassigned' } });
    res.json(meetingNames);
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch meetings' });
  }
});

// Organization: Get merged transcripts for a specific meeting name
router.get('/organization/meetings/:meetingName', authMiddleware, async (req, res) => {
  try {
    const { meetingName } = req.params;
    
    // Find all recordings (from ANY user) assigned to this meeting
    const recordings = await AudioRecording.find({ meetingName })
                                           .populate('userId', 'name')
                                           .select('-audioData');
    
    // We want to combine their transcripts dynamically and sort chronologically
    let combinedTranscript = [];

    recordings.forEach(rec => {
      if (rec.transcript && rec.transcript.length > 0) {
        const recordingStartTime = new Date(rec.createdAt).getTime();
        rec.transcript.forEach(t => {
          combinedTranscript.push({
            recordingId: rec._id,
            userName: rec.userId.name, // THE ACCOUNT NAME of whoever recorded it
            userId: rec.userId._id,
            text: t.text,
            timestamp: t.timestamp,
            absoluteTime: recordingStartTime + t.timestamp, // To sort across different files!
            endTime: t.endTime,
            aiSpeakerLabel: t.speaker // their local diarization label if any
          });
        });
      }
    });

    // Sort the master timeline chronologically across all users using true absolute times
    combinedTranscript.sort((a, b) => a.absoluteTime - b.absoluteTime);

    res.json({
      meetingName,
      participants: [...new Set(recordings.map(r => r.userId.name))],
      transcript: combinedTranscript,
      needsTranscription: recordings.some(rec => !rec.transcript || rec.transcript.length === 0)
    });

  } catch (err) {
    console.error('Org Meeting Error:', err);
    res.status(500).json({ error: 'Failed to fetch meeting transcripts' });
  }
});

// Organization: Bulk Transcribe an entire meeting
router.post('/organization/meetings/:meetingName/transcribe', authMiddleware, async (req, res) => {
  try {
    const { meetingName } = req.params;
    const recordings = await AudioRecording.find({ meetingName });

    for (const recording of recordings) {
      if (!recording.transcript || recording.transcript.length === 0) {
        console.log(`Transcribing missing recording for user ${recording.userId}...`);
        
        try {
          const transcriptInfo = await aiClient.transcripts.transcribe({
             audio: recording.audioData, 
             speaker_labels: true,
             speech_models: ["universal-3-pro"]
          });

          if (transcriptInfo.status !== 'error') {
            const SILENCE_THRESHOLD = 1500; 
            const finalBlocks = [];
            let currentBlock = null;

            if (transcriptInfo.words && transcriptInfo.words.length > 0) {
              transcriptInfo.words.forEach(word => {
                if (!currentBlock) {
                  currentBlock = { text: word.text, timestamp: word.start, endTime: word.end, speaker: word.speaker };
                } else {
                  if (word.speaker === currentBlock.speaker && (word.start - currentBlock.endTime) <= SILENCE_THRESHOLD) {
                    currentBlock.text += " " + word.text;
                    currentBlock.endTime = word.end;
                  } else {
                    finalBlocks.push(currentBlock);
                    currentBlock = { text: word.text, timestamp: word.start, endTime: word.end, speaker: word.speaker };
                  }
                }
              });
              if (currentBlock) finalBlocks.push(currentBlock);
            } else {
              finalBlocks.push(...(transcriptInfo.utterances || []).map(u => ({
                text: u.text, timestamp: u.start, endTime: u.end, speaker: u.speaker
              })));
            }
            recording.transcript = finalBlocks;
            await recording.save();
          }
        } catch (e) {
          console.error("Bulk AI Transcribe Error on a track:", e);
        }
      }
    }
    res.json({ message: 'Meeting transcription completed.' });
  } catch (err) {
    console.error('Bulk transcribe error:', err);
    res.status(500).json({ error: 'Failed to transcribe meeting.' });
  }
});

// Organization: Export to data1.json structured format
router.post('/organization/meetings/:meetingName/export', authMiddleware, async (req, res) => {
  try {
    const { meetingName } = req.params;
    
    const recordings = await AudioRecording.find({ meetingName })
                                           .populate('userId', 'name')
                                           .select('-audioData');
    
    let combinedTranscript = [];

    recordings.forEach(rec => {
      if (rec.transcript && rec.transcript.length > 0) {
        const recordingStartTime = new Date(rec.createdAt).getTime();
        rec.transcript.forEach(t => {
          combinedTranscript.push({
            userName: rec.userId.name,
            text: t.text,
            absoluteTime: recordingStartTime + t.timestamp,
          });
        });
      }
    });

    combinedTranscript.sort((a, b) => a.absoluteTime - b.absoluteTime);

    // Build the transcript string "Sarah: Hello. John: Hi!"
    const transcriptString = combinedTranscript.map(t => `${t.userName}: ${t.text}`).join(' ');
    
    const attendees = [...new Set(recordings.map(r => r.userId.name))];
    
    // Structure like data1.json
    const newStructuredMeeting = {
      id: `meeting_${Date.now()}`,
      title: meetingName,
      date: new Date().toISOString().split('T')[0],
      duration: 60, // Estimate or default
      attendees: attendees,
      transcript: transcriptString
    };

    // Save to data1.json file
    const dataPath = path.join(__dirname, '../data/data1.json');
    let dbData = { meetings: [] };
    if (fs.existsSync(dataPath)) {
      const rawData = fs.readFileSync(dataPath, 'utf8');
      try {
        dbData = JSON.parse(rawData);
        if (!dbData.meetings) dbData.meetings = [];
      } catch(e) {
        dbData = { meetings: [] };
      }
    }

    // Check if meeting already exists in file
    const existingIndex = dbData.meetings.findIndex(m => m.title === meetingName);
    if (existingIndex !== -1) {
      // Update existing meeting
      dbData.meetings[existingIndex] = newStructuredMeeting;
    } else {
      // Add new meeting
      dbData.meetings.push(newStructuredMeeting);
    }
    fs.writeFileSync(dataPath, JSON.stringify(dbData, null, 2), 'utf8');

    // Store in Database based on organization
    const orgId = req.user.id;
    let orgData = await OrganizationData.findOne({ organizationId: orgId });

    if (!orgData) {
      orgData = new OrganizationData({ organizationId: orgId, meetings: [] });
    }

    // Check if same meeting exists
    const existingMeetingIndex = orgData.meetings.findIndex(m => m.title === meetingName);

    if (existingMeetingIndex !== -1) {
      // Update existing
      orgData.meetings[existingMeetingIndex].transcript = newStructuredMeeting.transcript;
      orgData.meetings[existingMeetingIndex].attendees = newStructuredMeeting.attendees;
      orgData.meetings[existingMeetingIndex].date = newStructuredMeeting.date;
    } else {
      // Insert new meeting index array
      orgData.meetings.push(newStructuredMeeting);
    }

    await orgData.save();

    res.json({ message: 'Successfully exported formatted transcript and saved to MongoDB and data1.json!', meeting: newStructuredMeeting });
  } catch (err) {
    console.error('Export Data Error:', err);
    res.status(500).json({ error: 'Failed to export structured data.' });
  }
});

// Stream Audio Data from MongoDB
router.get('/stream/:id', async (req, res) => {
  try {
    const recording = await AudioRecording.findById(req.params.id);
    if (!recording || !recording.audioData) {
      return res.status(404).json({ message: 'Recording not found' });
    }

    const audioBuffer = Buffer.from(recording.audioData.buffer || recording.audioData);
    const total = audioBuffer.length;
    
    // Support HTTP Range Requests (Required by some browsers for <audio> elements)
    const range = req.headers.range;
    if (range) {
      const parts = range.replace(/bytes=/, "").split("-");
      const partialstart = parts[0];
      const partialend = parts[1];

      const start = parseInt(partialstart, 10);
      const end = partialend ? parseInt(partialend, 10) : total - 1;
      const chunksize = (end - start) + 1;

      res.writeHead(206, {
        'Content-Range': `bytes ${start}-${end}/${total}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunksize,
        'Content-Type': recording.contentType || 'audio/webm'
      });
      
      const chunk = audioBuffer.slice(start, end + 1);
      res.end(chunk);
    } else {
      res.writeHead(200, {
        'Content-Length': total,
        'Accept-Ranges': 'bytes',
        'Content-Type': recording.contentType || 'audio/webm'
      });
      res.end(audioBuffer);
    }
  } catch (err) {
    console.error('Stream Error:', err);
    res.status(500).json({ message: 'Server error streaming audio' });
  }
});

// Delete a specific recording
router.delete('/:id', authMiddleware, async (req, res) => {
  try {
    const recording = await AudioRecording.findById(req.params.id);
    
    // Ensure the recording exists and belongs to the user
    if (!recording) {
      return res.status(404).json({ message: 'Recording not found' });
    }
    
    if (recording.userId.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Not authorized to delete this recording' });
    }

    await AudioRecording.findByIdAndDelete(req.params.id);
    res.json({ message: 'Recording deleted successfully' });
  } catch (err) {
    console.error('Delete Error:', err);
    res.status(500).json({ message: 'Server error while deleting recording' });
  }
});

export default router;